name = "soeasyhub-v2"
main = "worker.js"
compatibility_date = "2024-04-03"

[site]
bucket = "./" # Local folder to upload

[vars]
SUPABASE_URL = "https://nbfzhxgkfljeuoncujum.supabase.co"

# Route to intercept soeasyhub.com traffic
[[routes]]
pattern = "soeasyhub.com/*"
zone_name = "soeasyhub.com"
